# Generated by Django 2.0.6 on 2018-06-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeman', '0002_usergroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='user_id',
            new_name='user',
        ),
    ]
