# Generated by Django 2.0.6 on 2018-06-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeman', '0003_auto_20180608_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together={('user', 'group')},
        ),
    ]
