# Generated by Django 2.0.6 on 2018-06-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeman', '0007_auto_20180610_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='codeman.Group'),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='codeman.User'),
        ),
    ]
